language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libsdl2-dev libsdl2-net-dev libogg-dev libvorbis-dev libavcodec-dev libavformat-dev libavutil-dev

  - git clone --depth 1 https://github.com/stalkerg/clunk.git /tmp/clunk
  - cd /tmp/clunk && cmake -DCMAKE_INSTALL_PREFIX=/usr . && make && sudo make install
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build && cmake .. && make
